# This workflow will do a clean install of node dependencies, regenerate the data/amp/src.json file and create a PR with any changes
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update AMP component versions

on:
    repository_dispatch:
        types: [amp-src]
    schedule:
        # * is a special character in YAML so you have to quote this string
        - cron: '0 0 1 * *'
jobs:
    genAmpSrc:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Set up node.js
              uses: actions/setup-node@v1
              with:
                  node-version: '12'

            - name: Install dependencies
              run: npm ci

            - name: Generate src.json
              run: npm run amp-src

            - name: Write commit message
              run: npm run release-notes --silent > /tmp/commit-message.txt

            - name: Read commit message
              id: msg
              uses: juliangruber/read-file-action@v1
              with:
                  path: /tmp/commit-message.txt

            - name: Show commit message
              run: |
                  OUT="${{ steps.msg.outputs.content }}"
                  OUT="${OUT//'%25'/'%'}"
                  OUT="${OUT//$'%0A'/'\n'}"
                  OUT="${OUT//$'%0D'/'\r'}"
                  echo -e "${OUT}"

            - name: Create pull request
              id: cpr
              uses: peter-evans/create-pull-request@v2
              with:
                  branch: amp-src
                  title: Update AMP component versions
                  body: ${{ steps.msg.outputs.content }}
                  commit-message: ${{ steps.msg.outputs.content }}

            - name: Show pull request number
              run: echo "PR \#${{ steps.cpr.outputs.pull-request-number }}"
